#!/bin/bash 
# Description:
#   My dotfile install script. Moves previous configurations
#   into `~/.dotfiles.old`
# Author:
#   Phoenix
# 

###############################
# =| Variables

BOLD=`tput bold`
STATUS=`tput setaf 4`
WARN=`tput setaf 3`
ERROR=`tput setaf 1`
RESET=`tput sgr0`

DOTFILES=( \
    ".zshrc" ".vimrc" ".gitignore" ".gitconfig" "Brewfile" ".tmux.conf" \
)

# Change this to decide where your dotfiles go
DOTFILESDIR=~/.dotfiles

GITHUB_RAW=https://raw.githubusercontent.com

###############################
# =| Functions

lk() {
    ln -sf $DOTFILESDIR/$1 ~/$1
}

lnk() {
    ln -sf $DOTFILESDIR/$1 ~/$2
}

status() {
    echo "${STATUS}${BOLD}[$1]${RESET}"
}

show_help() {
    cat <<EOF
Usage: install [options]

Options:
    -h, --help      Show this help message
    --version       Show the version

EOF

    exit 0
}

###############################
# =| Main
status "configuring"
printf "Is <\x1b[38;2;255;100;0mTHIS\x1b[0m> in red?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) HAS_TRUE_COLOR=1;;
        No ) HAS_TRUE_COLOR=0;;
    esac
done

status "install"

mkdir -p "$HOME/.zsh"

status "fetching utility programs"

echo "oh-my-zsh"
sh -c "$(curl -fsSL "${GITHUB_RAW}/ohmyzsh/ohmyzsh/master/tools/install.sh")"

echo "zsh-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
    "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

git clone "https://github.com/sindresorhus/pure.git" "$HOME/.zsh/pure"

status "linking"

for file in "${DOTFILES[@]}"; do
    echo $file
    if [ -f "~/$file" ]; then
        echo "~/$file already exists; backing it up as ~/dotfiles.old/$file/ ..."
        mv "~/$file" ~/.dotfiles.old/$file/
    fi

    lk "$file"
done

lnk custom .oh-my-zsh/custom
echo "HAS_TRUE_COLOR=${HAS_TRUE_COLOR}" > "custom/custom.zsh"
